### ISSUE TITLE
Both links in README to examples are now dead!

### ISSUE THREAD

**Issue by GregDavidson** [tiny-http/tiny-http#132]
Bottom of page:
-  https://github.com/tiny-http/tiny-http
Dead links:
- https://github.com/tiny-http/heroku-tiny-http-hello-world
- https://github.com/tiny-http/crate-deps

Hey everyone, do you have any other examples of tiny-http in action?  Especially small examples and demos?  The more the merrier!

**Comment by frewsxcv** [comment]
Fixed in https://github.com/tiny-http/tiny-http/commit/d8ba6a2caf53f996e00d0dec2498957ecc2542ee

Also, if you're looking for more examples: https://crates.io/crates/tiny_http/reverse_dependencies
