### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by est31** [tiny-http/tiny-http#161]
Hi, it would be cool to relicense `tiny-http` under the dual license terms `MIT OR Apache-2.0` (at the choice of the licensees) that are common in the Rust community.

To signify consent, please comment with the following:

```
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.
```

Thanks!

Contributor checkoff:
- [x] @tomaka
- [x] @frewsxcv
- [x] @Eijebong
- [x] @moises-silva
- [x] @ashleysommer
- [ ] @spk
- [ ] @erickt
- [x] @ebfe
- [x] @PENGUINLIONG
- [x] @zaneli
- [x] @tomprogrammer
- [x] @romanz
- [x] @phildawes
- [x] @ordepdev
- [x] @nikolaplejic
- [x] @mb64
- [x] @djc
- [x] @algesten

**Comment by Eijebong** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by frewsxcv** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by zaneli** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by mb64** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by moises-silva** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by tomprogrammer** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by romanz** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by ashleysommer** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by djc** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by nikolaplejic** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by ordepdev** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by algesten** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by ebfe** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by PENGUINLIONG** [comment]
I agree with relicensing my contributions to this work to the dual MIT/Apache-2.0 license.

**Comment by est31** [comment]
Friendly reminder to @spk @erickt @phildawes : could you please check whether you want to agree to this relicensing?

Also, their contributions seem fairly small so maybe we can just go forward with the relicensing.

**Comment by phildawes** [comment]
I can't remember what my contribution was, but I agree to this relicensing!

Thanks,

Phil

**Comment by pinkforest** [comment]
There is a dependency `chunked-transfer` that is only Apache 2.0 licensed, re-license here:
- https://github.com/frewsxcv/rust-chunked-transfer/pull/13
