### ISSUE TITLE
Fails to install with ascii 0.8.x being yanked from crates.io

### ISSUE THREAD

**Issue by gertvdijk** [tiny-http/tiny-http#162]
```
error: failed to select a version for the requirement `ascii = "^0.8"`
  candidate versions found which didn't match: 1.0.0, 0.9.3, 0.6.0, ...
  location searched: crates.io index
required by package `tiny_http v0.6.0`
```

It seems that versions 0.7.0-0.9.2 of the `ascii` package are [yanked from crates.io](https://crates.io/crates/ascii/versions) (wtf?), making tiny-http uninstallable at this moment.

**Comment by tomprogrammer** [comment]
Sorry for the breakage, these versions were yanked due to an unsoundness issue https://github.com/tomprogrammer/rust-ascii/issues/64. I've unyanked 0.8.7 until I publish a version 0.8.8 with a backported fix.

**Comment by gertvdijk** [comment]
FWIW, this was fixed in commit https://github.com/tiny-http/tiny-http/commit/fca82d369a03ef8ce69fbb477a594eba6a7c2765
