### ISSUE TITLE
Adding support for UnixStream sockets

### ISSUE THREAD

**Issue by fletcherw** [tiny-http/tiny-http#172]
Hi,

I'd be interested in using tiny-http in combination with UnixStream sockets. Would you be open to a pull request adding support for them behind a flag? I thought I'd add them as a third option in `refined_tcp_stream.rs` and then add a constructor to Server which accepts a UnixStream? This may require refactoring some of the functionality in Server::new into a function which is shared between the two.

**Comment by mpalmer** [comment]
I feel like this can probably be closed, since #224 has landed and been released.
