### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by bradfier** [tiny-http/tiny-http#199]
Hi Devs,

Thanks for all the work that's gone into this library over the last few years!

I want to check if there are plans to keep maintaining this crate. I've noticed that minor PRs have been left untouched for months, and while @frewsxcv has been triaging issues here and there, and @rawler has been reviewing PRs, there hasn't been much movement in the repo beyond security fixes.

I also saw that @tomaka said they were no longer maintaining the crate at all.

I've been extensively using Rouille and thus tiny-http in production for some time now, so if you do want to put the crate up for adoption, or if you just want someone else to deal with the issues and PRs, I'm ready to help.

**Comment by frewsxcv** [comment]
Thanks for reaching out @bradfier! I no longer have the bandwidth to help with maintaining tiny-http and am in favor of inviting you as a contributor to the project. Anyone else object?

**Comment by bradfier** [comment]
Excellent, I'm happy to help. :slightly_smiling_face:

**Comment by frewsxcv** [comment]
@bradfier Just sent you an invite

**Comment by bradfier** [comment]
Thanks @frewsxcv, accepted. Are you also able to add co-maintainers to crates.io or would you prefer to retain that responsibility yourself?

**Comment by frewsxcv** [comment]
> Thanks @frewsxcv, accepted. Are you also able to add co-maintainers to crates.io or would you prefer to retain that responsibility yourself?

Just sent you an invite to be a co-maintainer on crates.io
