### ISSUE TITLE
SSL configuration doesn't support certificate chains

### ISSUE THREAD

**Issue by YuhanLiin** [tiny-http/tiny-http#222]
When SSL is enabled for the server and the certificate buffer in the SSL configuration contains a chain of certificates, the server is only configured with the last certificate in the chain, rather than the whole chain. This is because the server calls `SslContext::set_certificate()`, which only sets one certificate even if it receives a whole chain. This leads to failures when connecting to a Rustls client, since Rustls expects the server to present a chain of certificates starting from the root CA. For example, I tested with [these certs](https://github.com/rustls/rustls/tree/main/test-ca/rsa). The Rustls client used `ca.cert`, while the `tiny-http` server used `end.fullchain` and `end.key`, and I got a TLS error on the client.

**Comment by bradfier** [comment]
Thanks for the bug report @YuhanLiin, coincidentally we noticed this mistake while working on Rustls support in https://github.com/tiny-http/tiny-http/commit/3e2ca0908365fb333751eb640d4cfa1cae05db04, I'll try and include a fix for the OpenSSL mode in that release when it's ready.

If you need this patched urgently though I would accept a PR which I can tidy up later.

**Comment by bradfier** [comment]
Fixed and released in [0.11.0](https://github.com/tiny-http/tiny-http/releases/tag/0.11.0), please let me know if you have any more issues!
